---
title: "Welcome to the BIC-ISMRM Web Admin Guide"
format: html
---

```{=html}
<head>
 <link rel="preconnect" href="https://fonts.googleapis.com">
 <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
 <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
</head>
```

This Web Admin Guide is the central resource for managing and maintaining the Chapter’s website (<https://bic.ismrm.org>).

The purpose is to maintain clear, open, and transparent documentation of website management processes, and serve as a shared reference that supports knowledge transfer, collaboration, and the long-term sustainability of the Chapter’s web presence.

It is designed to help current and future web management team members update and maintain the website with consistency and confidence.

## Overview

In this guide, you will find:

-   [**About**](/about.html)**:** Roles and responsibilities within the website management team.

-   [**Workflows**](/workflows.html)**:** Step-by-step instructions and procedures for updating content and managing different pages.

-   [**Style Guides**](/style-guides.html)**:** Chapter-specific standards for writing, branding, templates, and accessibility, aligned with ISMRM central office requirements while preserving the Chapter’s unique identity.
