---
title: "Workflows"
format: html
---

This page outlines the protocols and workflows for managing our chapter’s website, to support clear, open, and transparent operations for webite managers and contributors, ensuring consistency and continuity in maintaining the website.

## Header and Footer

-   Only the section under the “BIC Menu” is editable.
-   All other parts of the header and footer are maintained by the ISMRM central office.
-   Minor customisations to the header and footer are allowed in principle, but the core styling must remain intact.
-   Any proposed changes should be reviewed in coordination with the ISMRM central office to ensure compliance with the core styling.

## Committee Members

### Current Members

For each committee member, gather the following:

-   Photo (square format preferred)
-   Full name
-   Executive Committee position
-   Primary affiliated institution and City

Before publishing, confirm all details with each member individually.

### Past Members

-   Review the Chapter’s newsletters. These are the primary source for past committee members.
-   If information is missing or unclear, reach out to the chapter's Executive Committee.
-   Arrange members in reverse chronological order, i.e. most recent first.
-   Use the format: Full Name, Years Served. For example, John Doe, 2024-2025.
-   For the following roles, include additional details in parentheses:
    -   Annual Meeting Organiser: add the meeting location. For example: John Doe, 1995 (Oxford)
    -   Industrial Representative: add the company. For example: Jane Doe, 2000 (Company)

## Funding and Recognition

### Bill Moore Lecture Recipients

-   Refer to the programme of the Chapter’s Annual Meeting, where the Bill Moore Lecture recipient is typically listed.\
-   Record the recipient’s name and the city of the annual meeting.
-   If any of the details are unclear, confirm with the Chapter’s Executive Committee.

### Mansfield Research Innovation Award

::: callout-note
This is not the Siemens Mansfield Innovation Award presented at the ISMRM annual meeting.
:::

-   Check the Chapter's Newsletters - this is typically where the winners are announced.
-   If affliation information is missing, start with an online search (e.g., institutional websites, LinkedIn, PubMed) to verify the awardees' affiliations.
-   For older or unclear entries, reach out to the chapter's Executive Committee for further details.

## MR Education Series

To be added.

## Newsletter

To be added.

## Jobs

-   The chapter does not maintain its own job board. At present, visitors are redirected to the ISMRM & ISMRT Career Center (<https://www.ismrm.org/career-center/>). 

## Contacts

-   Ensure that the information on Contacts page is kept up to date.
-   Ensure that the general contact email ([bicismrm\@ismrm.org](mailto:bicismrm@ismrm.org)) is used consistently across all communication platforms.

::: callout-note
The Chapter’s general enquiries email address is [bicismrm\@ismrm.org](mailto:bicismrm@ismrm.org). Messages sent to this address are automatically forwarded to the current Chapter President. The Web Management Team can provide technical support related to the mailbox if needed, but does not oversee its content or day-to-day management.
:::
